matrix:
  include:
    - language: java
      install: true
      jdk:
        - openjdk12
      script:
        - ./gradlew build

    - language: generic
      services:
        - docker
      env:
        - BUILD_NAME=docker_scraper
        - RELEASE=`echo $TRAVIS_BRANCH | sed -E "s/\//-/g" | sed -e 's/\(.*\)/\L\1/'`
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker build -t doerfli/feedscraper_scraper:$RELEEASE -f Dockerfile-scraper .
        - docker push doerfli/feedscraper_scraper:$RELEASE


    - language: generic
      services:
        - docker
      env:
        - BUILD_NAME=docker_viewer
        - RELEASE=`echo $TRAVIS_BRANCH | sed -E "s/\//-/g" | sed -e 's/\(.*\)/\L\1/'`
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker build -t doerfli/feedscraper_viewer:$RELEASE -f Dockerfile-viewer .
        - docker push doerfli/feedscraper_viewer:$RELEASE
