matrix:
  include:
    - language: java
      install: true
      jdk:
        - openjdk12
      script:
        - ./gradlew build

    - language: generic
      services:
        - docker
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker build -t doerfli/feedscraper_scraper:$TRAVIS_BRANCH -f Dockerfile-scraper .
        - docker push doerfli/feedscraper_scraper:$TRAVIS_BRANCH
      env:
        - BUILD_NAME=docker_scraper

    - language: generic
      services:
        - docker
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker build -t doerfli/feedscraper_viewer:$TRAVIS_BRANCH -f Dockerfile-viewer .
        - docker push doerfli/feedscraper_viewer:$TRAVIS_BRANCH
      env:
        - BUILD_NAME=docker_viewer
