matrix:
  include:
    - language: java
      install: true
      jdk:
        - openjdk12
      script:
        - cd scraper
        - ./gradlew build
      env:
        - BUILD_NAME=scraper
    - language: java
      install: true
      jdk:
        - openjdk12
      script:
        - cd viewer
        - ./gradlew build
      env:
        - BUILD_NAME=viewer

    - language: generic
      services:
        - docker
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker build -t doerfli/feedscraper_scraper:latest scraper
        - docker push doerfli/feedscraper_scraper:latest
      env:
        - BUILD_NAME=docker_scraper

    - language: generic
      services:
        - docker
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker build -t doerfli/feedscraper_viewer:latest viewer
        - docker push doerfli/feedscraper_viewer:latest
      env:
        - BUILD_NAME=docker_viewer
