#= Build ============================================================
FROM openjdk:12.0.1-jdk-oraclelinux7 as build
WORKDIR /workspace

COPY build.gradle .
COPY gradle.properties .
COPY gradlew .
COPY settings.gradle .
COPY gradle gradle
COPY common common
COPY scraper scraper


RUN ./gradlew -Dorg.gradle.daemon=false :scraper:assemble
RUN mkdir -p scraper/build/libs/dependency && (cd scraper/build/libs/dependency; jar -xf ../*.jar)

#= Run ==============================================================
FROM openjdk:12.0.1-jdk-oraclelinux7

VOLUME /tmp
VOLUME /log

COPY --from=build /workspace/scraper/build/libs/dependency/BOOT-INF/lib /app/lib
COPY --from=build /workspace/scraper/build/libs/dependency/META-INF /app/META-INF
COPY --from=build /workspace/scraper/build/libs/dependency/BOOT-INF/classes /app

ENTRYPOINT java -cp app:app/lib/* li.doerf.feeder.scraper.ScraperApplicationKt
