#= Build ============================================================
FROM adoptopenjdk/openjdk13-openj9:alpine-slim as build
WORKDIR /workspace

COPY build.gradle .
COPY gradle.properties .
COPY gradlew .
COPY settings.gradle .
COPY gradle gradle
COPY common common
COPY viewer viewer

RUN ./gradlew -Dorg.gradle.daemon=false :viewer:assemble
RUN mkdir -p viewer/build/libs/dependency && (cd viewer/build/libs/dependency; jar -xf ../*.jar)

#= Run ==============================================================
FROM adoptopenjdk/openjdk13-openj9:alpine-slim

VOLUME /tmp
VOLUME /log

COPY --from=build /workspace/viewer/build/libs/dependency/BOOT-INF/lib /app/lib
COPY --from=build /workspace/viewer/build/libs/dependency/META-INF /app/META-INF
COPY --from=build /workspace/viewer/build/libs/dependency/BOOT-INF/classes /app

ENTRYPOINT java -Xtune:virtualized -cp app:app/lib/* li.doerf.feeder.viewer.ViewerApplicationKt
