version: '3'
services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mqtt:
    image: eclipse-mosquitto:1.6
    restart: always
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_data:/mosquitto/data
    ports:
      - "1883:1883"
      - "9001:9001"
  scraper:
    image: doerfli/feedscraper_scraper
    build: 
      context: .
      dockerfile: Dockerfile-scraper
    restart: always
    depends_on:
      - db
      - viewer
  viewer:
    image: doerfli/feedscraper_viewer
    build: 
      context: .
      dockerfile: Dockerfile-viewer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
