version: '3'
services:
  db:
    image: postgres:11.3-alpine
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  scraper:
     image: doerfli/feedscraper_scraper
    build: 
      context: .
      dockerfile: Dockerfile-scraper
    restart: always
    depends_on:
      - db
  viewer:
    image: doerfli/feedscraper_viewer
    build: 
      context: .
      dockerfile: Dockerfile-viewer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
